apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: homework
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: dmitry8000/homework-order-service:latest
        ports:
        - containerPort: 5004
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: "http://+:5004"
        - name: ConnectionStrings__DefaultConnection
          value: "Host=postgres-orders-service;Port=5432;Database=orders_db;Username=postgres;Password=postgres"
        - name: BillingService__BaseUrl
          value: "http://billing-service:5003/"
        - name: RabbitMQ__HostName
          value: "rabbitmq-service"
        - name: RabbitMQ__Port
          value: "5672"
        - name: RabbitMQ__UserName
          value: "guest"
        - name: RabbitMQ__Password
          value: "guest"
        - name: RabbitMQ__ExchangeName
          value: "order.events"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5004
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5004
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: homework
spec:
  selector:
    app: order-service
  ports:
  - protocol: TCP
    port: 5004
    targetPort: 5004
  type: ClusterIP
